
name: Deploy to Page on Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Puedes ajustar la versión de Node.js según tus necesidades

    - name: Install Dependencies
      run: npm install

    # - name: Deploy to Page
    #   run: npm run deploy
    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.TOKEN_GITHUB }}
        repository: ${{ github.repository }}

    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}